version: '3.8'
services:
  backend:
    image: greedybnbusdt/backend:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      EXCHANGE_CLIENT_BINANCE_API_KEY: your_binance_api_key
      EXCHANGE_CLIENT_BINANCE_API_SECRET: your_binance_api_secret
    volumes:
      - './logs:/app/logs'
